service: lovlettr-api

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-west-2

  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        #lovlettr
      Resource: "arn:aws:dynamodb:us-west-2:*:*"

functions:
  create:
    handler: src/handlers/letter.createLtr
    events:
      - http:
          path: ltr/create
          method: post
          cors: true

  get:
    handler: src/handlers/letter.getLtr
    events:
      - http:
          path: ltr/{letterId}
          method: get
          cors: true

  delete:
    handler: src/handlers/letter.deleteLtr
    events:
      - http:
          path: ltr/delete
          method: delete
          cors: true

  put:
    handler: src/handlers/letter.updateLtr
    events:
      - http:
          path: ltr/update
          method: put
          cors: true
